# Run Verb-Object-Extraction with Sample Dataset

In [1]:
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler()
    ]
)

import pandas as pd
from verb_object_extraction import search_pairs_in_jobads

2026-08-04 14:29:06,805 [INFO] 321 Verben
2026-08-04 14:29:06,815 [INFO] 648 Derivate
2026-08-04 14:29:06,816 [INFO] 627 Derivate unique
2026-08-04 14:29:07,113 [INFO] number of pairs: 4390
2026-08-04 14:29:07,160 [INFO] number of verbs: 321

In [2]:
jobad_df = pd.read_csv('../data/sample_jobads.csv')
print(len(jobad_df))
jobad_df.head()

50

   id                                         jobad_text
0   0    Elektromaschinenmonteur/in (Formspulwicklung...
1   1  BÃ¤ckereiverkÃ¤ufer als Quereinsteiger (m/w/d)...
2   2  Technischer Zeichner EPlan (m/w/d) Großraum [A...
3   3  [ANONYM]\n\n[ANONYM]\n\nMeister/ Techniker/ In...
4   4    Microsoft Professional, skype for business, ...

In [3]:
pairs_df = search_pairs_in_jobads(jobad_df, text_column='jobad_text')
print(len(pairs_df))
pairs_df.head()

2026-08-04 14:29:10,593 [INFO] search verb object pairs in 50 jobads (column: jobad_text)
2026-08-04 14:29:14,601 [INFO] preprocessed jobads with spacy
2026-08-04 14:29:15,082 [INFO] found 181 new pairs

181

,id,sentence,Task_Dimension,verb,object,derivate,compound,distance
0,0,*** Übrigens: Informationen zu unserem Unterne...,Interactive,informieren,Unternehmen,Information,None,3
2,1,* Fachkompetente und serviceorientierte Kunden...,Interactive,beraten,Kunde,None,Kundenberatung,0
3,1,"Kundenberatung, -betreuung.",Interactive,beraten,Kunde,None,Kundenberatung,0
4,1,Firmeninformation:,Interactive,informieren,Firma,None,Firmeninformation,0
1,1,Dabei unterstÃ¼tzen und beraten wir Dich jeder...,Interactive,beraten,Partner,None,None,6

In [4]:
pairs_df['Task_Dimension'].value_counts()

Task_Dimension
Interactive    63
Kognition      63
Analytic       21
Autonomy       19
Manual         15
Name: count, dtype: int64